### ISSUE TITLE
Question: Usage of    /react-native-windows/webdriver.git

### ISSUE THREAD

**Issue by serhatbolsu** [react-native-windows/winappdriver-js-webdriver-example#459]
Hi,

Knowing that this README is written last year, does it still make sense to use 
`    "webdriver": "git+https://github.com/react-native-windows/webdriver.git",`

Can you please share why is it required or is it better to stick with default webdriver now

fyi: I am using webdriverIO to drive winappdriver for now

**Comment by licanhua** [comment]
No. It doesn't need it any more.
The workaround was for [Azure Pipeline](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md), and now WinAppDriver 1.2.2009.02003 is pre-installed(was 1.1 before).
WinAppDriver supports WebDriverIO since v1.2-RC and workaround was needed

**Comment by serhatbolsu** [comment]
Thank you , this is good clarification for me
